name: Poll Microsoft Graph CallRecords
on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  poll:
    runs-on: ubuntu-latest
    steps:
      - name: Invoke pollCallRecords
        run: |
          curl -s -X GET "https://briefly-theta.vercel.app/api/graph/pollCallRecords" \
            -H "Accept: application/json" \
            -o /dev/null && echo "Polled successfully"
